### ISSUE TITLE
Memory corruption crash when passing enough text files to exceed 256 globals

### ISSUE THREAD

**Issue by nyanpasu64** [KungFuFurby/AddMusicKFF#262]
https://github.com/KungFuFurby/AddMusicKFF/blob/fabfabfc7fe271645932158317061cb99872b885/src/AddmusicK/AddmusicK.cpp#L231-L238

This code is a user-controlled loop where `textFilesToCompile.size()` is increased by passing more files on the command line. `musics` has length 256. If `highestGlobalSong + i` is 255, then `highestGlobalSong + i >= 256` doesn't get triggered, but `highestGlobalSong + 1 + i` is 256, an out-of-bounds index triggering an instant segfault crash in Valgrind or regular execution, or a `double free or corruption (out)` on program shutdown in gdb.

I'm not sure if the `+ 1` should be present in both the bounds check and the indexing, or neither. If I add `+ 1` to the bounds check, I get no crash in Valgrind or regular execution.

**Comment by KungFuFurby** [comment]
The safest bet I can think of is to add the `+ 1` to the bounds check.

**Comment by nyanpasu64** [comment]
I *think* this issue and the odd `+1` scattered about, results from AMK using `highestGlobalSong` rather than something like `globalMusicCount`.

As mentioned in #263, when you remove all global songs and try compiling a text file, `highestGlobalSong` is 0 even though song 0 isn't valid. I *think* it tries opening `openTextFile((std::string("music/") + musics[i + highestGlobalSong].name), musics[i + highestGlobalSong].text);`, where `i` is 0 and `highestGlobalSong` is 0, and the name is empty. So AMK crashes opening a directory as a file.

IMO this is two bugs: `highestGlobalSong` is 0 when song 0 isn't present, and `i + highestGlobalSong` is missing `+ 1` (which *should* make the code not work, I don't know why it works at all). My preferred approach is to switch to `globalMusicCount` with value `highestGlobalSong + 1`, and rewrite the remainder of the program around this. I actually implemented it locally, and it works for the 0 global songs case, but I didn't test thoroughly to ensure it doesn't break other use cases.

**Comment by KungFuFurby** [comment]
My main concern about this approach is the SNES side code (which I noticed in your commit): namely, zero is essentially used there as a NOP and for retriggering purposes, hence the off-by-one cases.
